### ISSUE TITLE
benthos cuelang is another option

### ISSUE THREAD

**Issue by gedw99** [sudo-suhas/play-script-engine#1]
really nice repo.

in case you did not know, you can use CueLang to define Benthos processing. 
its strongly types and also compositional so you an build huge processing pipelines with runtime and compile time checking.

GenType for all your  benthos processors. With these types, users can build complex configurations using helpers to reduce the boilerplate, that would otherwise be present when working with YAML, while benefiting from strong type checking!
```
benthos list --format cue 
```

you might also be into this https://github.com/disintegrator/benthos-pg-listen

**Comment by sudo-suhas** [comment]
I have added a readme to the repo to clarify the purpose. Not entirely sure where CueLang could fit into it.
